### ISSUE TITLE
Composer is asking for git@git.uhin.org password

### ISSUE THREAD

**Issue by P3AdminAccount** [UHIN/x12-parser-library#3]
I have added:
"repositories" : [
    {
     "type": "vcs",
     "url": "ssh://git@git.uhin.org/shr/x12-parser.git"
    }
     ]
to the composer.json file and it when running: composer require uhin/x12-parser:1.0.0 it is giving mye the following prompt:
git@git.uhin.org's password:

If I try to install without the repositories section, it gets installed by composer and when I try to run the basic sample, I get the following error message:

Warning: include(Uhin\X12Parser\Parser\X12Parser.php): failed to open stream: No such file or directory

Here is my code:
 require __DIR__ . '/vendor/autoload.php';
use Uhin\X12Parser\Parser\X12Parser;
$parser = new X12Parser($x12);
print_r($parser->parse());

**Comment by rmclellanduhin** [comment]
This is just an issue with the README from when we were only using this internally. If you use the composer install option listed below the VCS include it should work properly.

**Comment by rmclellanduhin** [comment]
We will make sure to update the README to reference this properly in the future.
